# Generated by Django 5.2.1 on 2025-05-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
